# Generated by Django 3.2.20 on 2023-08-17 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cas_server', '0001_squashed_0013_auto_20170329_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federateduser',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
